version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: forum
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: forumdb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  api:
    build: ./apps/api
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://forum:secret@db:5432/forumdb
      - THREAD_SERVICE_URL=http://thread:3000/threads
    networks:
      - backend
    restart: unless-stopped

  thread:
    build: ./apps/thread
    ports:
      - "80:3000"  # Port 80 côté hôte, 3000 côté conteneur (Vite preview)
    environment:
      - API_URL=http://api:3000/threads
    networks:
      - backend
    restart: unless-stopped

  sender:
    build: ./apps/sender
    ports:
      - "8080:3000" # Port 8080 côté hôte, 3000 dans le conteneur (Vite ou autre)
    environment:
      - API_URL=http://api:3000/threads
    networks:
      - backend
    restart: unless-stopped

volumes:
  db-data:

networks:
  backend:
