name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

# Permissions globales pour le workflow
permissions:
  contents: read
  packages: write
  id-token: write

# Variables d'environnement globales pour le registre Docker
env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  # Détection de secrets dans le code
  secret-scan:
    name: Secret Detection
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Récupère tout l'historique pour scanner tous les commits
      
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  # Analyse SAST (Static Application Security Testing)
  sast-analysis:
    name: SAST Analysis
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          queries: security-and-quality
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  validate:
    name: Lint and Format
    needs: [secret-scan, sast-analysis]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Lint
        run: pnpm lint
        
      - name: Format check
        run: pnpm format:check || true # Continue même si la vérification échoue

  test:
    name: Run Tests
    needs: validate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Run tests
        run: pnpm test

  build-and-push-images:
    name: Build and Push Docker Images
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write  # Essentiel pour publier des packages
    strategy:
      matrix:
        service: [api, thread, sender]
        include:
          - service: api
            context: ./apps/api
          - service: thread
            context: ./apps/thread
          - service: sender
            context: ./apps/sender

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Conversion du nom du repo en minuscules (requis par ghcr.io)
      - name: Convert repository name to lowercase
        id: repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # Extraction du hash court du commit pour les tags d'image
      - name: Extract commit short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Authentification au GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Construction et publication de l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          provenance: false
          tags: |
            ${{ env.REGISTRY }}/${{ steps.repo_name.outputs.REPO_NAME }}/${{ matrix.service }}:latest
            ${{ env.REGISTRY }}/${{ steps.repo_name.outputs.REPO_NAME }}/${{ matrix.service }}:${{ steps.sha.outputs.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to AWS
    needs: build-and-push-images
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Extract commit short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Télécharger le state précédent s'il existe
      - name: Download Terraform state
        uses: dawidd6/action-download-artifact@v3
        continue-on-error: true
        with:
          name: terraform-state
          path: ./terraform
          workflow: ci-cd.yml
          branch: ${{ github.ref_name }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan \
            -var="docker_image_tag=${{ steps.sha.outputs.SHORT_SHA }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      # Sauvegarder le state pour les prochains runs
      - name: Upload Terraform state
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: terraform-state
          path: |
            ./terraform/terraform.tfstate
            ./terraform/terraform.tfstate.backup
          retention-days: 90

      - name: Get deployment outputs
        working-directory: ./terraform
        id: outputs
        run: |
          echo "api_url=$(terraform output -raw api_url)" >> $GITHUB_OUTPUT
          echo "thread_url=$(terraform output -raw thread_url)" >> $GITHUB_OUTPUT
          echo "sender_url=$(terraform output -raw sender_url)" >> $GITHUB_OUTPUT
          echo "db_ip=$(terraform output -raw db_public_ip)" >> $GITHUB_OUTPUT

      - name: Deployment Summary
        run: |
          echo "## 🚀 Deployment Successful - 4 EC2 Instances!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Services URLs:" >> $GITHUB_STEP_SUMMARY
          echo "- **Thread** (view messages): ${{ steps.outputs.outputs.thread_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Sender** (post messages): ${{ steps.outputs.outputs.sender_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **API** (backend): ${{ steps.outputs.outputs.api_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Database**: ${{ steps.outputs.outputs.db_ip }}:5432" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Both frontend apps (Thread & Sender) run on port 80!" >> $GITHUB_STEP_SUMMARY
