name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

# Variables d'environnement globales pour le registre Docker
env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}

jobs:
  validate:
    name: Lint and Format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Lint
        run: pnpm lint
        
      - name: Format check
        run: pnpm format:check || true # Continue même si la vérification échoue

  test:
    name: Run Tests
    needs: validate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Run tests
        run: pnpm test

  build-and-push-images:
    name: Build and Push Docker Images
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write  # Essentiel pour publier des packages
    strategy:
      matrix:
        service: [api, thread, sender]
        include:
          - service: api
            context: ./apps/api
          - service: thread
            context: ./apps/thread
          - service: sender
            context: ./apps/sender

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Conversion du nom du repo en minuscules (requis par ghcr.io)
      - name: Convert repository name to lowercase
        id: repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # Extraction du hash court du commit pour les tags d'image
      - name: Extract commit short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Authentification au GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Construction et publication de l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.repo_name.outputs.REPO_NAME }}/${{ matrix.service }}:latest
            ${{ env.REGISTRY }}/${{ steps.repo_name.outputs.REPO_NAME }}/${{ matrix.service }}:${{ steps.sha.outputs.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Generate Deployment Artifact
    needs: build-and-push-images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Convert repository name to lowercase
        id: repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        
      - name: Extract commit short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Update docker-compose.yml with image tags
        run: |
          sed -i 's|build: ./apps/api|image: ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}/api:${{ steps.sha.outputs.SHORT_SHA }}|g' docker-compose.yml
          sed -i 's|build: ./apps/thread|image: ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}/thread:${{ steps.sha.outputs.SHORT_SHA }}|g' docker-compose.yml
          sed -i 's|build: ./apps/sender|image: ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}/sender:${{ steps.sha.outputs.SHORT_SHA }}|g' docker-compose.yml
          
      - name: Save docker-compose.yml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: docker-compose.yml
          retention-days: 7
